export interface ApiResponse<T> {
  data: T;
  meta: { timestamp: string; requestId: string };
  error?: { code: string; message: string; field?: string };
}

export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
}

export interface HubUserDto {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  status: string;
  manufacturerId?: string;
  lastLoginAt?: string;
  roles: string[];
  programIds: string[];
  createdAt: string;
}

export interface ManufacturerDto {
  id: string;
  name: string;
  status: string;
  primaryContactName?: string;
  primaryContactEmail?: string;
  primaryContactPhone?: string;
  contractReference?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ProgramDto {
  id: string;
  manufacturerId: string;
  manufacturerName: string;
  name: string;
  drugBrandName: string;
  drugGenericName?: string;
  ndcCodes?: string;
  therapeuticArea?: string;
  status: string;
  programStartDate?: string;
  programEndDate?: string;
  createdAt: string;
}

export interface ProgramConfigDto {
  id: string;
  programId: string;
  paRequired: boolean;
  adherenceProgramEnabled: boolean;
  remsTrackingEnabled: boolean;
  enrollmentSources: string;
  miRequiredForErx: boolean;
  copayEnabled: boolean;
  papEnabled: boolean;
  bridgeEnabled: boolean;
  copayIncomeLimitEnabled?: boolean;
  copayIncomeLimitFplPct?: number;
  copayMonthlyCapUsd?: number;
  copayAnnualCapUsd?: number;
  papFplThresholdPct?: number;
  papAllowCommercialInsured?: boolean;
  bridgeTriggerPaPending?: boolean;
  bridgeTriggerCoverageLapse?: boolean;
  bridgeTriggerNewEnrollment?: boolean;
  bridgeSupplyDays?: number;
  bridgeMaxEpisodesPerYear?: number;
  papSupplyDays?: number;
  paSlaSumbitDays?: number;
  paSlaFollowupDays?: number;
  paAppealWindowDays?: number;
  paAutoEscalateOnBreach?: boolean;
  consentUrlExpiryDays?: number;
}

export interface PatientDto {
  id: string;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  gender?: string;
  phoneMobile?: string;
  phoneHome?: string;
  email?: string;
  addressLine1?: string;
  addressLine2?: string;
  city?: string;
  state?: string;
  zip?: string;
  preferredLanguage?: string;
  preferredContactMethod?: string;
}

export interface PrescriberDto {
  id: string;
  npi?: string;
  firstName: string;
  lastName: string;
  credential?: string;
  practiceName?: string;
  phone?: string;
}

export interface CaseDto {
  id: string;
  caseNumber: string;
  programId: string;
  programName: string;
  drugBrandName: string;
  manufacturerName: string;
  patient: PatientDto;
  prescriber?: PrescriberDto;
  assignedCmId?: string;
  assignedCmName?: string;
  stage: string;
  status: string;
  enrollmentSource?: string;
  consentStatus: string;
  consentReceivedAt?: string;
  miStatus?: string;
  priority: string;
  slaBreachFlag: boolean;
  escalationFlag: boolean;
  closedReason?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface CaseTaskDto {
  id: string;
  caseId: string;
  caseNumber: string;
  patientName: string;
  programName: string;
  taskType: string;
  title: string;
  status: string;
  priority: string;
  dueDate?: string;
  assignedTo?: string;
  assignedToName?: string;
  completedAt?: string;
  notes?: string;
  autoGenerated: boolean;
  createdAt: string;
}

export interface TimelineEntryDto {
  id: string;
  type: string;
  summary: string;
  details?: string;
  performedBy: string;
  timestamp: string;
}

export interface PriorAuthorizationDto {
  id: string;
  caseId: string;
  paNumber?: string;
  attemptNumber: number;
  status: string;
  submittedDate?: string;
  submissionMethod?: string;
  decisionDate?: string;
  denialReasonText?: string;
  slaSubmitDeadline?: string;
  slaBreached: boolean;
}

export interface InsurancePlanDto {
  id: string;
  caseId: string;
  planSequence: string;
  insuranceTypeCode: string;
  payerName?: string;
  planName?: string;
  memberId?: string;
  groupId?: string;
}

export interface FinancialAssistanceCaseDto {
  id: string;
  caseId: string;
  faType: string;
  status: string;
  fplPercentageCalculated?: number;
  incomeVerified?: boolean;
  approvalDate?: string;
  expiryDate?: string;
  benefitAmountMonthly?: number;
}

export interface Page<T> {
  content: T[];
  totalElements: number;
  totalPages: number;
  number: number;
  size: number;
}

/** Human-readable labels for case stages */
export const STAGE_LABELS: Record<string, string> = {
  'Referral': 'Referral',
  'Enrollment': 'Enrollment',
  'BIVB': 'BI/BV',
  'PA': 'PA',
  'FinancialAssist': 'Financial Assist',
  'Initiation': 'Initiation',
  'Adherence': 'Adherence',
  'Closed': 'Closed',
};

export function stageLabel(stage: string): string {
  return STAGE_LABELS[stage] || stage;
}
