package com.hubaccess.domain.activity;

import com.hubaccess.domain.auth.HubUser;
import com.hubaccess.domain.cases.HubCase;
import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

@Entity
@Table(name = "case_task")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CaseTask {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "case_id", nullable = false)
    private HubCase hubCase;

    @Column(name = "task_type", nullable = false, length = 30)
    private String taskType;

    @Column(nullable = false, length = 300)
    private String title;

    @Column(nullable = false, length = 20)
    @Builder.Default
    private String status = "Open";

    @Column(nullable = false, length = 10)
    @Builder.Default
    private String priority = "Normal";

    @Column(name = "due_date")
    private LocalDate dueDate;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assigned_to")
    private HubUser assignedTo;

    @Column(name = "completed_at")
    private Instant completedAt;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "completed_by")
    private HubUser completedBy;

    @Column(columnDefinition = "TEXT")
    private String notes;

    @Column(name = "auto_generated")
    @Builder.Default
    private Boolean autoGenerated = false;

    @Column(name = "created_at", nullable = false, updatable = false)
    @Builder.Default
    private Instant createdAt = Instant.now();

    @Column(name = "updated_at", nullable = false)
    @Builder.Default
    private Instant updatedAt = Instant.now();

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by")
    private HubUser createdByUser;

    @PreUpdate
    protected void onUpdate() {
        updatedAt = Instant.now();
    }
}
