CREATE TABLE IF NOT EXISTS program (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  manufacturer_id UUID NOT NULL REFERENCES manufacturer(id),
  name VARCHAR(200) NOT NULL,
  drug_brand_name VARCHAR(200) NOT NULL,
  drug_generic_name VARCHAR(200),
  ndc_codes TEXT,
  therapeutic_area VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active','Inactive','Pilot')),
  program_start_date DATE,
  program_end_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID
);

CREATE TABLE IF NOT EXISTS program_config (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  program_id UUID NOT NULL UNIQUE REFERENCES program(id),
  pa_required BOOLEAN NOT NULL DEFAULT true,
  adherence_program_enabled BOOLEAN NOT NULL DEFAULT true,
  rems_tracking_enabled BOOLEAN NOT NULL DEFAULT false,
  enrollment_sources VARCHAR(20) NOT NULL DEFAULT 'Both' CHECK (enrollment_sources IN ('Portal','eRX','Both')),
  mi_required_for_erx BOOLEAN NOT NULL DEFAULT true,
  mi_required_fields JSONB,
  copay_enabled BOOLEAN NOT NULL DEFAULT false,
  pap_enabled BOOLEAN NOT NULL DEFAULT false,
  bridge_enabled BOOLEAN NOT NULL DEFAULT false,
  copay_income_limit_enabled BOOLEAN DEFAULT false,
  copay_income_limit_fpl_pct INTEGER,
  copay_monthly_cap_usd INTEGER,
  copay_annual_cap_usd INTEGER,
  copay_enrollment_months INTEGER DEFAULT 12,
  copay_min_age INTEGER DEFAULT 18,
  pap_fpl_threshold_pct INTEGER,
  pap_allow_commercial_insured BOOLEAN DEFAULT false,
  pap_proof_of_income_required BOOLEAN DEFAULT true,
  pap_attestation_only BOOLEAN DEFAULT false,
  pap_supply_days INTEGER DEFAULT 90,
  pap_enrollment_months INTEGER DEFAULT 12,
  pap_min_age INTEGER DEFAULT 18,
  bridge_trigger_pa_pending BOOLEAN DEFAULT true,
  bridge_trigger_coverage_lapse BOOLEAN DEFAULT true,
  bridge_trigger_new_enrollment BOOLEAN DEFAULT true,
  bridge_supply_days INTEGER DEFAULT 30,
  bridge_max_episodes_per_year INTEGER DEFAULT 1,
  bridge_new_patient_only BOOLEAN DEFAULT false,
  bridge_income_limit_enabled BOOLEAN DEFAULT false,
  bridge_income_limit_fpl_pct INTEGER,
  pa_sla_submit_days INTEGER DEFAULT 3,
  pa_sla_followup_days INTEGER DEFAULT 5,
  pa_appeal_window_days INTEGER DEFAULT 30,
  pa_auto_escalate_on_breach BOOLEAN DEFAULT true,
  consent_url_expiry_days INTEGER DEFAULT 7,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
