CREATE TABLE IF NOT EXISTS financial_assist_case (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES hub_case(id) ON DELETE CASCADE,
  fa_type VARCHAR(10) NOT NULL CHECK (fa_type IN ('Copay','PAP','Bridge')),
  status VARCHAR(20) NOT NULL DEFAULT 'Evaluating' CHECK (status IN ('Evaluating','Eligible','Ineligible','Approved','Active','Expired','Denied')),
  annual_household_income DECIMAL(12,2),
  household_size INTEGER,
  fpl_percentage_calculated DECIMAL(6,2),
  income_verified BOOLEAN DEFAULT false,
  income_verification_method VARCHAR(20) CHECK (income_verification_method IN ('Document','Attestation')),
  eligibility_determined_at TIMESTAMPTZ,
  eligibility_determined_by UUID REFERENCES hub_user(id),
  approval_date DATE,
  expiry_date DATE,
  benefit_amount_monthly DECIMAL(10,2),
  benefit_ytd_used DECIMAL(10,2) DEFAULT 0,
  bridge_supply_days_authorized INTEGER,
  bridge_ship_date DATE,
  denial_reason TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS prior_authorization (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES hub_case(id) ON DELETE CASCADE,
  pa_number VARCHAR(100),
  attempt_number INTEGER NOT NULL DEFAULT 1,
  parent_pa_id UUID REFERENCES prior_authorization(id),
  status VARCHAR(20) NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft','Submitted','UnderReview','Approved','Denied','Appealed','Withdrawn')),
  submitted_date DATE,
  submission_method VARCHAR(20) CHECK (submission_method IN ('Portal','Fax','Phone','Electronic')),
  payer_id VARCHAR(100),
  submitted_by UUID REFERENCES hub_user(id),
  decision_date DATE,
  effective_date DATE,
  expiry_date DATE,
  denial_reason_code VARCHAR(50),
  denial_reason_text TEXT,
  appeal_deadline DATE,
  sla_submit_deadline DATE,
  sla_breached BOOLEAN DEFAULT false,
  clinical_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS patient_outreach (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID NOT NULL REFERENCES hub_case(id) ON DELETE CASCADE,
  outreach_type VARCHAR(20) NOT NULL CHECK (outreach_type IN ('Consent','MI','RefillReminder','AdherenceCheckin','PAStatus','Other')),
  channel VARCHAR(10) NOT NULL DEFAULT 'SMS' CHECK (channel IN ('SMS')),
  phone_number VARCHAR(20) NOT NULL,
  sent_at TIMESTAMPTZ NOT NULL,
  sent_by UUID REFERENCES hub_user(id),
  unique_url VARCHAR(500),
  access_code VARCHAR(20),
  url_expires_at TIMESTAMPTZ,
  responded BOOLEAN DEFAULT false,
  responded_at TIMESTAMPTZ,
  response_channel VARCHAR(10) CHECK (response_channel IN ('Portal','Chat')),
  attempt_number INTEGER DEFAULT 1,
  message_body TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
