package com.hubaccess.domain.activity.dto;

import lombok.*;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class CaseTaskDto {
    private UUID id;
    private UUID caseId;
    private String caseNumber;
    private String patientName;
    private String programName;
    private String taskType;
    private String title;
    private String status;
    private String priority;
    private LocalDate dueDate;
    private UUID assignedTo;
    private String assignedToName;
    private Instant completedAt;
    private String notes;
    private Boolean autoGenerated;
    private Instant createdAt;
}
